"""PyVista conversion helpers with affine-exact NIfTI slice geometry.

This module is a standalone replacement candidate for
``src/tractfigure/vtk_conversion.py``.  It does not modify a repository.
"""

from collections.abc import Sequence

import nibabel as nib
import numpy as np
import pyvista as pv
from nibabel.affines import apply_affine


def streamlines_to_polydata(
    streamlines: tuple[np.ndarray, ...],
    max_streamlines: int | None = None,
) -> pv.PolyData:
    selected = streamlines

    if max_streamlines is not None and len(selected) > max_streamlines:
        indices = np.linspace(
            0,
            len(selected) - 1,
            num=max_streamlines,
            dtype=int,
        )
        selected = tuple(selected[index] for index in indices)

    points = np.concatenate(selected, axis=0)
    line_array_size = sum(len(streamline) + 1 for streamline in selected)
    lines = np.empty(line_array_size, dtype=np.int64)

    point_offset = 0
    line_offset = 0

    for streamline in selected:
        number_of_points = len(streamline)

        lines[line_offset] = number_of_points
        lines[line_offset + 1 : line_offset + 1 + number_of_points] = np.arange(
            point_offset,
            point_offset + number_of_points,
            dtype=np.int64,
        )

        point_offset += number_of_points
        line_offset += number_of_points + 1

    polydata = pv.PolyData(points)
    polydata.lines = lines
    return polydata


def nifti_to_image_data(image: nib.spatialimages.SpatialImage) -> pv.ImageData:
    """Convert a 3D NIfTI image into world-coordinate PyVista ImageData.

    This remains available for volume-oriented operations.  Use
    :func:`nifti_to_orthogonal_slices` for display slices because some VTK
    filters do not preserve oriented ``vtkImageData`` direction matrices.
    """

    image = nib.as_closest_canonical(image)
    data = np.asarray(image.dataobj, dtype=np.float32)

    if data.ndim != 3:
        raise ValueError(f"Expected a 3D image; received shape {data.shape}")

    affine = np.asarray(image.affine, dtype=float)
    basis = affine[:3, :3]
    spacing = np.linalg.norm(basis, axis=0)

    if np.any(spacing <= 0):
        raise ValueError("Image affine contains invalid voxel spacing")

    direction = basis / spacing

    if not np.allclose(direction.T @ direction, np.eye(3), atol=1e-4):
        raise ValueError("The initial viewer does not support sheared image affines")

    grid = pv.ImageData(
        dimensions=data.shape,
        spacing=spacing,
        origin=affine[:3, 3],
        direction_matrix=direction,
    )
    grid.point_data["intensity"] = data.ravel(order="F")
    return grid


def _validate_slice_indices(
    shape: tuple[int, int, int],
    indices: Sequence[int] | None,
) -> tuple[int, int, int]:
    if indices is None:
        return tuple(size // 2 for size in shape)

    if len(indices) != 3:
        raise ValueError("Slice indices must contain exactly three values")

    validated = tuple(int(value) for value in indices)
    for axis, (value, size) in enumerate(zip(validated, shape, strict=True)):
        if not 0 <= value < size:
            raise ValueError(
                f"Slice index {value} is outside axis {axis} with size {size}"
            )
    return validated


def _slice_to_structured_grid(
    data: np.ndarray,
    affine: np.ndarray,
    axis: int,
    index: int,
) -> pv.StructuredGrid:
    varying_axes = tuple(candidate for candidate in range(3) if candidate != axis)
    first_axis, second_axis = varying_axes

    first, second = np.meshgrid(
        np.arange(data.shape[first_axis], dtype=float),
        np.arange(data.shape[second_axis], dtype=float),
        indexing="ij",
    )

    voxel_coordinates = np.empty((*first.shape, 3), dtype=float)
    voxel_coordinates[..., axis] = float(index)
    voxel_coordinates[..., first_axis] = first
    voxel_coordinates[..., second_axis] = second

    world_coordinates = apply_affine(
        affine,
        voxel_coordinates.reshape(-1, 3),
    ).reshape(*first.shape, 3)

    grid = pv.StructuredGrid(
        world_coordinates[..., 0],
        world_coordinates[..., 1],
        world_coordinates[..., 2],
    )

    if axis == 0:
        intensity = data[index, :, :]
    elif axis == 1:
        intensity = data[:, index, :]
    else:
        intensity = data[:, :, index]

    grid.point_data["intensity"] = np.asarray(
        intensity,
        dtype=np.float32,
    ).ravel(order="F")
    grid.field_data["voxel_axis"] = np.asarray([axis], dtype=np.int32)
    grid.field_data["voxel_index"] = np.asarray([index], dtype=np.int32)
    return grid


def nifti_to_orthogonal_slices(
    image: nib.spatialimages.SpatialImage,
    indices: Sequence[int] | None = None,
) -> dict[str, pv.StructuredGrid]:
    """Create sagittal, coronal, and axial slices in exact NIfTI world space.

    Each displayed point is generated by applying the canonical NIfTI affine
    directly to an integer voxel center.  This avoids an oriented-image filter
    step and therefore keeps the anatomy in the same RASMM coordinate system as
    the tract actors.
    """

    canonical = nib.as_closest_canonical(image)
    data = np.asarray(canonical.dataobj, dtype=np.float32)

    if data.ndim != 3:
        raise ValueError(f"Expected a 3D image; received shape {data.shape}")

    affine = np.asarray(canonical.affine, dtype=float)
    slice_indices = _validate_slice_indices(data.shape, indices)

    return {
        "sagittal": _slice_to_structured_grid(
            data,
            affine,
            axis=0,
            index=slice_indices[0],
        ),
        "coronal": _slice_to_structured_grid(
            data,
            affine,
            axis=1,
            index=slice_indices[1],
        ),
        "axial": _slice_to_structured_grid(
            data,
            affine,
            axis=2,
            index=slice_indices[2],
        ),
    }
